var products=[
    {
        'id' : 1,
        'nombre' : 'Bogotá',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 2,
        'nombre' : 'Medellín',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 3,
        'nombre' : 'Cali',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 4,
        'nombre' : 'Cartagena',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 1,
        'nombre' : 'Caldas',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 5,
        'nombre' : 'Manizales',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 6,
        'nombre' : 'Cúcuta',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 7,
        'nombre' : 'Pereira',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
    {
        'id' : 8,
        'nombre' : 'Ibagué',
        'tipo' : 'lager',
        'grados' : 4.2,
        'precio' : 12900,
        'image' : "https://via.placeholder.com/150",
    },
  ]

